spring.datasource.url=jdbc:hsqldb:file:islamic-studies
spring.datasource.username=SA
spring.datasource.password=secr#t
spring.datasource.driver-class-name=org.hsqldb.jdbc.JDBCDriver

spring.jpa.database-platform=org.hibernate.dialect.HSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true